<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Numpy Ladder Challenge - Notebook 2

_Author:_ Tim Book

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. In this ladder challenge, we'll learn some core math concepts, some linear algebra, and the `numpy` library. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

Additionally, since not all of the topics discussed in this ladder challenge are explicitly taught in our course, these problems come with many more hints, tips, suggestions, and even sometimes a mini-lesson. You are encouraged to Google frequently throughout the lesson. In many ways, this ladder is meant to be a challenge as well as educational in its own right.

**Remember our one rule: NO LOOPS! None of the exercises in this notebook require a loop. If you use a loop to solve any of these problems, you are solving the problem incorrectly.**

0) Import numpy in the usual way

In [1]:
import numpy as np

# Section III - Simulation
In the next section, we'll use functions within the `np.random` submodule. You can find documentation [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html).

27) Generate 10,000 random numbers between 0 and 1 and assign them to a variable. To verify you've simulated the data properly, make sure the mean is approximately 0.5.

In [2]:
x = np.random.random(10_000)
x.mean()

0.49981881022144053

28) What proportion of these numbers is below 0.1?

In [3]:
(x < 0.1).mean()

0.101

29) What proportion of these numbers is above 0.8?

In [4]:
(x > 0.8).mean()

0.1995

30) What proportion of these numbers is above 0.2 but below 0.3?

In [5]:
((x > 0.2) & (x < 0.3)).mean()

0.0975

31) Generate 10,000 random numbers between 2 and 4. To verify you've simulated the data properly, find the mean and make sure it is approximately what you expect.

* _Hint:_ There is no `numpy` function for this specifically. How can you use the function you just used to generate this?

In [6]:
ary_2_4 = 2 + 2 * np.random.random(10_000)
ary_2_4.mean()

2.9976416259389724

32) What proportion of these numbers is between 2.4 and 2.6?

In [7]:
((ary_2_4 > 2.4) & (ary_2_4 < 2.6)).mean()

0.1022

33) Generate 100,000 random standard normal (i.e., mean 0 standard deviation 1) numbers. Again, find the mean to verify you've done this properly.

In [8]:
array_normal = np.random.standard_normal(100_000)
print('Mean:', array_normal.mean().round(2))
print('STD:', array_normal.std().round(2))

Mean: -0.0
STD: 1.0


34) What proportion of these numbers is negative?

In [9]:
(array_normal < 0).mean()

0.50186

35a) What proportion of these numbers is between -1 and 1?

In [10]:
((array_normal > -1) & (array_normal < 1)).mean()

0.68418

35b) What proportion of these numbers is between -2 and 2?

In [11]:
((array_normal > -2) & (array_normal < 2)).mean()

0.95517

35c) What proportion of these numbers is between -3 and 3? Have you seen your last 3 solutions before? (If you've taken an intro stats course in college before, you will have.)

In [12]:
((array_normal > -3) & (array_normal < 3)).mean()

0.99758

### For the next few problems, we will be playing Rock-Paper-Scissors
If you are unfamiliar with the game Rock-Paper-Scissors, it features two combatants choosing one of three hand motions: rock, paper, or scissors. Rock beats scissors, scissors beats paper, and paper beats rock. Two friends are playing: Karen and Tom. Unbeknownst to them, you've been studying and recording both of their play patterns. Karen chooses rock 40% of the time, paper 10% of the time, and scissors 50% of the time. For Tom, it's rock 10%, paper 60%, scissors 30%. Who wins the most often?

**This is an extremely difficult question.** We will get to the answer in a few guided steps. You'll want to use `np.random.choice()` to help you through this.

36) Create vectors `p_karen` and `p_tom` that represent their respective probabilities for rock, paper, and scissors.

In [13]:
p_karen = [0.4, 0.1, 0.5]
p_tom = [0.1, 0.6, 0.3]

37) Simulate 5 games. Who wins the majority of them? Just eyeball this one. (No one wins a draw.)

In [14]:
choices = ['rock', 'paper', 'scissors']
print('Karen:', np.random.choice(a=choices, size=5, p=p_karen))
print('Tom:', np.random.choice(a=choices, size=5, p=p_tom))

Karen: ['scissors' 'scissors' 'scissors' 'scissors' 'scissors']
Tom: ['paper' 'paper' 'paper' 'paper' 'paper']


38) Let's write a function to handle _one game at a time_. Write a function called `rps` that takes two arguments: `karen` and `tom` that will be either `"R"`, `"P"`, or `"S"`. The function will return `"K"`, `"T"`, or `"D"`, representing Karen, Tom, or a draw. That is, the function should give the following results:

* `rps("R", "P") ==> "T"`
* `rps("R", "S") ==> "K"`
* `rps("R", "R") ==> "D"`


* _Hint:_ Your answer will be a mess of `if`/`elif` statements.

In [15]:
def rps(karen, tom):
    if karen == 'R':
        if tom == 'P':
            return 'T'
        elif tom == 'S':
            return 'K'
    elif karen == 'P':
        if tom == 'R':
            return 'K'
        elif tom == 'S':
            return 'T'
    elif karen == 'S':
        if tom == 'R':
            return 'T'
        elif tom == 'P':
            return 'K'
    return 'D'

In [16]:
# Validate rps function
for i in ['R', 'P', 'S']:
    for j in ['R', 'P', 'S']:
        print(f"rps({i}, {j}) ==> {rps(i, j)}")

rps(R, R) ==> D
rps(R, P) ==> T
rps(R, S) ==> K
rps(P, R) ==> K
rps(P, P) ==> D
rps(P, S) ==> T
rps(S, R) ==> T
rps(S, P) ==> K
rps(S, S) ==> D


39) As it stands now, the function you have written cannot handle vector data. Luckily, `numpy` gives us a function that allows us to vectorize any function we want. Use `np.vectorize` to create `rps_vectorized`, the vectorized version of `rps`. Skim the docs [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html).

In [17]:
rps_vectorized = np.vectorize(rps)

40) Simulate 1,000,000 (yes, one million) games. How often does Karen win? You can find the results by:

1. Replicating your solution to problems 37 and 38, except for one million instead of 5.
1. Using the function you made in problem 39.


* _Note 1:_ These probabilities are relatively difficult to figure out by hand. Some probabilities are best discovered by simulation. Another way of asking the above question is "What is the probability of Karen winning?")
* _Note 2:_ Look what we did! We used vectorization to completely eliminate the need for a loop! You _could_ have solved this problem with a loop, but it would have taken significantly more computer time.

In [18]:
choices = ['R', 'P', 'S']
# Simulation 1M times of RPS game
results = rps_vectorized(np.random.choice(a=choices, size=1_000_000, p=p_karen), 
               np.random.choice(a=choices, size=1_000_000, p=p_tom))

In [19]:
# Calculate winning probability for Karen and Tom
print('Karen winning prob:', (results == 'K').mean())
print('Tom winning prob:', (results == 'T').mean())
print('Drawing prob:', (results == 'D').mean())

Karen winning prob: 0.429964
Tom winning prob: 0.320646
Drawing prob: 0.24939


### Regression Simulation
Next, suppose we're trying to simulate some fake data for a regression problem we wish to give to our students. We wish to simulate data for the following equation:

$$y = 1000 + 200x + \varepsilon$$

Where $\varepsilon \sim N(0, 20)$ (that is, $\varepsilon$ is normally distributed with mean 0 and standard deviation 20).

41) Generate 10 $x$s from the $N(50, 10)$ distribution. (That is, the normal distribution with mean 50 and standard deviation 10).

In [20]:
xs = np.random.normal(50, 10, 10)

In [21]:
xs

array([54.04232152, 51.54318812, 54.11783284, 64.45554813, 57.50230919,
       57.9706097 , 62.30607938, 50.47096929, 57.93770085, 56.54854548])

In [22]:
# Check result
print('Shape', xs.shape)
print('Mean:', xs.mean())
print('STD:', xs.std())

Shape (10,)
Mean: 56.6895104505969
STD: 4.177474332469891


42) Generate 10 $\varepsilon$s from the appropriate distribution described above.

In [23]:
es = np.random.normal(0, 20, 10)

In [24]:
# Check result
print('Shape', es.shape)
print('Mean:', es.mean())
print('STD:', es.std())

Shape (10,)
Mean: -8.61333337737889
STD: 23.462553892297187


43) Simulate the $y$s as described above using the two vectors you made in the previous two problems.

In [25]:
ys = 1000 + 200*xs + es
ys

array([11841.70688724, 11295.62137802, 11794.40140746, 13886.71075409,
       12501.57119653, 12549.0137018 , 13486.74224969, 11092.94940448,
       12559.49095524, 12284.67963286])

# Section IV: Matrices
_Tiny note:_ In general, we have told you it's against Python's style guide to use capital letters when defining variables. The one exception we make is when our variables represent mathematical objects. So feel free to name the following variables things like `A`, `B`, etc.!

44) Create the following matrix:

$$
A =
\begin{bmatrix}
3 & -1 & 5 \\
-2 & 0 & 8 \\
4 & 5 & -7
\end{bmatrix}
$$

In [26]:
A = np.array(
    [[3, -1, 5],
     [-2, 0, 8],
     [4, 5, -7]]
)
A

array([[ 3, -1,  5],
       [-2,  0,  8],
       [ 4,  5, -7]])

45) Create the following matrix:

$$
B =
\begin{bmatrix}
-3 & 8 & 2 \\
2 & -3 & 5 \\
0 & 6 & -2
\end{bmatrix}
$$

In [27]:
B = np.array(
    [[-3, 8, 2],
     [2, -3, 5],
     [0, 6, -2]]
)
B

array([[-3,  8,  2],
       [ 2, -3,  5],
       [ 0,  6, -2]])

46) Use `np.eye()` to create the following matrix:

$$
I = I_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

In [28]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

47) Triple every element of `B`. (Do not reassign.)

In [29]:
np.power(B, 3)

array([[-27, 512,   8],
       [  8, -27, 125],
       [  0, 216,  -8]], dtype=int32)

48) Index `A` in order to get me -7.

In [30]:
A[-1][-1]

-7

49) Index `A` in order to get me 0.

In [31]:
A[1][1]

0

50) Index `A` to get me $\begin{bmatrix} -2 & 0 & 8 \end{bmatrix}$

In [32]:
A[1]

array([-2,  0,  8])

51) Index `A` to get me
$$
\begin{bmatrix}
-1 \\ 0 \\ 5
\end{bmatrix}
$$

(You can ignore the fact that it may print out as a row vector)

In [33]:
A[:, 1]

array([-1,  0,  5])

52) Index `A` to get me
$$
\begin{bmatrix}
0 & 8 \\
5 & -7 
\end{bmatrix}
$$

In [34]:
A[1:, 1:]

array([[ 0,  8],
       [ 5, -7]])

53) Redefine the middle column of `A` to be
$$
\begin{bmatrix}
-2 \\ 1 \\ 7
\end{bmatrix}
$$

In [35]:
A[:, 1] = [-2, 1, 7]
A

array([[ 3, -2,  5],
       [-2,  1,  8],
       [ 4,  7, -7]])

54) Index `B` to define the following matrix:
$$
C = 
\begin{bmatrix}
8 & 2 \\
-3 & 5 \\
6 & -2
\end{bmatrix}
$$

In [36]:
C = B[:, 1:]
C

array([[ 8,  2],
       [-3,  5],
       [ 6, -2]])

55) What is $A + B$?

In [37]:
A + B

array([[ 0,  6,  7],
       [ 0, -2, 13],
       [ 4, 13, -9]])

56) What is $2A - 3B$?

In [38]:
2*A - 3*B

array([[ 15, -28,   4],
       [-10,  11,   1],
       [  8,  -4,  -8]])

57) What is the elementwise product of $A$ and $B$?

In [39]:
A * B

array([[ -9, -16,  10],
       [ -4,  -3,  40],
       [  0,  42,  14]])

58) What is $AB$?

In [40]:
np.dot(A, B)

array([[-13,  60, -14],
       [  8,  29, -15],
       [  2, -31,  57]])

59) What is $BA$? And why isn't it the same as $AB$?

In [41]:
np.dot(B, A)

# The reason that AB is not equal to BA is
# Imagine that A and B is tranformations of a vector
# the last tranformation, if considering AB then B is last tranformation,
# explain how a original vector is rotated. And the first tranformation,
# in this case A, explain how a rotated vector is sheared.

# In summary, the order of A and B are matter because
# if A and B are swaped, how original vector is rotated and shared will be changed.

array([[-17,  28,  35],
       [ 32,  28, -49],
       [-20,  -8,  62]])

60) What is $AI$, and is it equal to $IA$? Does this product look familiar?

In [42]:
np.dot(A, I)

array([[ 3., -2.,  5.],
       [-2.,  1.,  8.],
       [ 4.,  7., -7.]])

In [43]:
np.dot(I, A)

array([[ 3., -2.,  5.],
       [-2.,  1.,  8.],
       [ 4.,  7., -7.]])

In [44]:
# AI and IA is the same and also the same as original A.
# So, I is identity matrix. When the identity matrix multiply by other matrix,
# it will give the same result as the matrix that is multiplied by the identity.

61) What is $AC$?

In [45]:
np.dot(A, C)

array([[ 60, -14],
       [ 29, -15],
       [-31,  57]])

62) Why do we get an error when calculating $CA$?

In [46]:
# np.dot(C, A)
# The condition of array dimension is not satisfied.
# Number of columns of first matrix must be equal to number of rows of second matrix.

63) What is $A^TA$? Note that you answer will be a _diagonal matrix_, that is, a matrix that is equal to its transpose.

In [47]:
np.dot(A.T, A)

array([[ 29,  20, -29],
       [ 20,  54, -51],
       [-29, -51, 138]])

64) What is $A^TB$?

In [48]:
np.dot(A.T, B)

array([[-13,  54, -12],
       [  8,  23, -13],
       [  1, -26,  64]])

65) What is $A^{-1}$ (the inverse of $A$).

In [49]:
np.invert(A)

array([[-4,  1, -6],
       [ 1, -2, -9],
       [-5, -8,  6]], dtype=int32)

66) What is $AA^{-1}$? Does it look familiar?

* _Hint:_ Maybe call an `np.round()` on your result.

In [50]:
np.dot(A, np.linalg.inv(A)).round(2)

# It returns an identify matrix.

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

67) What is $(B + A^TA)^{-1}A^TC$?

In [51]:
np.dot(np.linalg.inv(B + np.dot(A.T,A)), np.dot(A.T, C))

array([[ 3.00215282, -0.28385833],
       [-0.62588766,  0.33839645],
       [ 0.24189329,  0.52202903]])